name: docs
on:
  push:
    branches: [master]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install oj-verify
        run: pip install online-judge-verify-helper
      - name: Run oj-verify docs
        run: oj-verify docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .verify-helper/markdown
          enable_jekyll: true
