name: verify

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install tools
        run: |
          pip install online-judge-verify-helper
          pip install online-judge-tools

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-script
        run: dotnet tool install -g dotnet-script

      - name: Add PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run verify
        run: oj-verify run