name: verify

on:
  push:

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install tools
        run: |
          pip install online-judge-verify-helper
          pip install online-judge-tools

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-script
        run: dotnet tool install -g dotnet-script

      - name: Add PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run verify
        run: oj-verify run

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run oj-verify docs
        run: oj-verify docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .verify-helper/markdown
          enable_jekyll: true